### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by okg00dbye** [jialin7878/3D-block-game#1]
features
- [ ] add opposite camera angle
- [ ] add top down view
- [ ] add hold block (doing)
- [ ] add settings
- [x] link to playfab, make actual leaderboard
- [ ] add quit/retry to pause screen

fixes
- [ ] fix rotations
- [ ] fix leaderboard not loading
- [ ] add camera to pan up automatically

extras
- [ ] add cool particle effects, animations
- [ ] add sound effects
- [ ] start menu animations

others
- [ ] faster drop rate over time?
